name: athletiqo
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  intl: ^0.20.2
  http: ^1.3.0
  mime: ^2.0.0
  path: ^1.9.1
  http_parser: ^4.1.2
  connectivity_plus: ^6.1.4
  lottie: ^3.3.1
  logger: ^2.5.0
  iconsax: ^0.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  syncfusion_flutter_charts: ^29.1.40
  flutter_slidable: ^4.0.0
  image_picker: ^1.1.2
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  flutter_native_splash: ^2.4.6
  cloud_functions: ^5.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/loggo.png"

flutter:

  uses-material-design: true

    #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/animations/
    - assets/brands/
    - assets/onboarding/
    - assets/payment_methods/
    - assets/reviews/
    - assets/user/
    - assets/logo/
    - assets/screenshots/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
